version: "3.8"

volumes:
   mongo_vol:

networks:
  rotten_net:
    driver: bridge

services:
  app:
    image: giozandonai/rotten-potatoes:v1
    build: 
      context: ./src
    container_name: app
    depends_on:
      - mongo-db
    ports:
      - 8080:5000
    environment:
      MONGODB_DATABASE: ${DB_DATABASE}
      MONGODB_HOST: mongo-db
      MONGODB_PORT: 27017
      MONGODB_USERNAME: ${DB_USER}
      MONGODB_PASSWORD: ${DB_PWD}     
    networks:
      - rotten_net

  mongo-db:
    image: mongo:4.4.3
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_vol:/data/db
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PWD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}     
    networks:
      - rotten_net

  mongo-exp:
    image: mongo-express
    container_name: mongo-exp
    restart: always
    depends_on:
      - mongo-db
    ports:
      - 8090:8081
    environment:      
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PWD}
    networks:
      - rotten_net